apiVersion: 1

datasources:
  - name: PostgreSQL Fertility
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    password: senha
    user: postgres
    database: fertility_gold
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      sslmode: "disable"
      defaultRegion: "default"
    secureJsonData:
      password: senha
